New log file opened at Tue Mar 08 06:18:47 CST 2016 by 6700@DOPE
Taking next connection to: 59241
New client attempting to connect on port: 59242-59241
  Address = /192.168.0.2:59241
This client on port 59242 has uuid 8ca11527-c799-47d8-8e39-e1e393368d0e configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: play-fork-run-8ca11527-c799-47d8-8e39-e1e393368d0e
Taking next connection to: 59241
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 59241
New client attempting to connect on port: 59487-59241
  Address = /192.168.0.2:59241
Handshake exception on socket: 59487
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 59241
New client attempting to connect on port: 59488-59241
  Address = /192.168.0.2:59241
This client on port 59488 has uuid 181531c8-c107-4af4-bbb1-87f9fdfa6207 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: play-fork-run-181531c8-c107-4af4-bbb1-87f9fdfa6207
Taking next connection to: 59241
